language: csharp
solution: Chrysalis.sln
install:
  - nuget restore Chrysalis.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
mono:
  - latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - xbuild /p:Configuration=Release Chrysalis.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Chrysalis.Core.UnitTests/bin/Release/Chrysalis.Core.UnitTests.dll